FROM oven/bun:1.1.34 AS build
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

FROM oven/bun:1.1.34 AS run
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY --from=build /app/.output /app/.output

EXPOSE 3000
CMD ["bun", ".output/server/index.mjs"]

