# Stage 1: Builder
# Меняем версию на запрошенную
FROM golang:1.25.5-alpine AS builder

WORKDIR /app

# Копируем файлы зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем статический бинарник
# CGO_ENABLED=0 критично для Alpine, чтобы бинарник не требовал библиотек libc
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Stage 2: Runner
FROM alpine:latest

WORKDIR /root/

# Копируем бинарник из билдера
COPY --from=builder /app/main .
# Копируем статику
COPY --from=builder /app/public ./public

EXPOSE 8080

CMD ["./main"]
